### ISSUE TITLE
Timezone not respected when using mlforecaster

### ISSUE THREAD

**Issue by sti0** [davidusb-geek/emhass#128] opened 2023-10-29 07:29 UTC
**Describe the bug**
After changing DST in Europe (CEST->CST) the output of the `mlforecaster` is in the wrong timezone (UTC instead local TZ).

**To Reproduce**
Predict a ML model

**Expected behavior**
Predict values in the right timezone

**Screenshots**
![image](https://github.com/davidusb-geek/emhass/assets/18382402/dd7e3e1e-c8a0-4e34-8303-7b8f25aed91b)

**Home Assistant installation type**
 - Home Assistant OS

**Your hardware**
- OS: HA OS
- Architecture: amd64

**EMHASS installation type**
 - Add-on

**Additional context**
Works using MPC:
![image](https://github.com/davidusb-geek/emhass/assets/18382402/131798db-1470-4fa2-a461-2f2175321f7d)

**Comment by ronaldt80** [comment] 2023-10-29 15:15
Same here, i use mpc but all optimizations are one hour off.

**Comment by adammcdonagh** [comment] 2023-10-29 21:12
I'm going to assume my problem is related too? It started from yesterday morning... If I turn `mlforecaster` off and use just `naive` I get no errors, but obviously not great...

```
2023-10-29 21:09:52,111 - web_server - ERROR - Exception on /action/naive-mpc-optim [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 179, in action_call
    input_data_dict = set_input_data_dict(config_path, str(data_path), costfun,
  File "/usr/local/lib/python3.9/dist-packages/emhass/command_line.py", line 120, in set_input_data_dict
    P_load_forecast = fcst.get_load_forecast(method=optim_conf['load_forecast_method'], set_mix_forecast=True, df_now=df_input_data)
  File "/usr/local/lib/python3.9/dist-packages/emhass/forecast.py", line 615, in get_load_forecast
    forecast_out = mlf.predict(data_last_window)
  File "/usr/local/lib/python3.9/dist-packages/emhass/machine_learning_forecaster.py", line 206, in predict
    predictions = self.forecaster.predict(steps=self.lags_opt,
  File "/usr/local/lib/python3.9/dist-packages/skforecast/ForecasterAutoreg/ForecasterAutoreg.py", line 696, in predict
    if self.differentiation is not None:
AttributeError: 'ForecasterAutoreg' object has no attribute 'differentiation'
```

**Comment by robinostlund** [comment] 2023-10-31 17:44
If you are using docker, have you mounted this volume? - '/etc/localtime:/etc/localtime:ro'

**Comment by adammcdonagh** [comment] 2023-10-31 18:15
> If you are using docker, have you mounted this volume? - '/etc/localtime:/etc/localtime:ro'

I’m using the HA Addon. So that’s not configurable.

**Comment by davidusb-geek** [comment] 2023-11-01 03:18
This is all related to #126.
Catching this specific case should solve the issue. I need to spend some time on this.
However if you retrain the model the problem is still there?

**Comment by sti0** [comment] 2023-11-01 08:01
No, even after running fit, tune and predict ( in that order) the predict output is 1h behind in my case and prints UTC instead of the local time in the web ui (2023-11-01 08:00:00+00:00 instead of 9am). 

Just to mention again, MPC shows the right time values in the web ui. So I'm not sure if this is the same issue.

**Comment by sti0** [comment] 2023-11-01 08:05
BTW. The published sensor in HA shows the wrong timezone setting, too.

Compared with a deferrable load sensor:
![image](https://github.com/davidusb-geek/emhass/assets/18382402/3bb69f6d-96ae-4d58-9c1f-6b83cc3dc349)

![image](https://github.com/davidusb-geek/emhass/assets/18382402/4e749a1a-ca71-463d-a821-40983f5860bb)

**Comment by davidusb-geek** [comment] 2024-01-04 09:32
Hi is this still a current issue. There were some changes in time zone handling of the latest versions. Hopefully this was solved.

**Comment by davidusb-geek** [comment] 2024-02-09 09:14
I am closing this as the latest changes on handling TZ should improve this.
Also a solution could be to just retrain your ML forecaster model after the DST change.
Go to the `share` folder, erase the corresponding `.pkl` file, then retrain the ML forecaster model.

**Closed by davidusb-geek** 2024-02-09 09:14 UTC
Labels: duplicate
